"""db update 0.02

Revision ID: 004b113a45c4
Revises: b14cb192568e
Create Date: 2020-05-26 13:18:32.587460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004b113a45c4'
down_revision = 'b14cb192568e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_info_con', table_name='info')
    op.create_index(op.f('ix_info_con'), 'info', ['con'], unique=False)
    op.drop_index('ix_info_date', table_name='info')
    op.create_index(op.f('ix_info_date'), 'info', ['date'], unique=False)
    op.drop_index('ix_info_lat', table_name='info')
    op.create_index(op.f('ix_info_lat'), 'info', ['lat'], unique=False)
    op.drop_index('ix_info_lon', table_name='info')
    op.create_index(op.f('ix_info_lon'), 'info', ['lon'], unique=False)
    op.drop_index('ix_info_time', table_name='info')
    op.create_index(op.f('ix_info_time'), 'info', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_info_time'), table_name='info')
    op.create_index('ix_info_time', 'info', ['time'], unique=1)
    op.drop_index(op.f('ix_info_lon'), table_name='info')
    op.create_index('ix_info_lon', 'info', ['lon'], unique=1)
    op.drop_index(op.f('ix_info_lat'), table_name='info')
    op.create_index('ix_info_lat', 'info', ['lat'], unique=1)
    op.drop_index(op.f('ix_info_date'), table_name='info')
    op.create_index('ix_info_date', 'info', ['date'], unique=1)
    op.drop_index(op.f('ix_info_con'), table_name='info')
    op.create_index('ix_info_con', 'info', ['con'], unique=1)
    # ### end Alembic commands ###
