"""db update 0.01

Revision ID: b14cb192568e
Revises: 
Create Date: 2020-05-26 12:18:57.893276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14cb192568e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('time', sa.String(length=12), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('con', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_info_con'), 'info', ['con'], unique=True)
    op.create_index(op.f('ix_info_date'), 'info', ['date'], unique=True)
    op.create_index(op.f('ix_info_lat'), 'info', ['lat'], unique=True)
    op.create_index(op.f('ix_info_lon'), 'info', ['lon'], unique=True)
    op.create_index(op.f('ix_info_time'), 'info', ['time'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_info_time'), table_name='info')
    op.drop_index(op.f('ix_info_lon'), table_name='info')
    op.drop_index(op.f('ix_info_lat'), table_name='info')
    op.drop_index(op.f('ix_info_date'), table_name='info')
    op.drop_index(op.f('ix_info_con'), table_name='info')
    op.drop_table('info')
    # ### end Alembic commands ###
